name: aegis_app
description: A example app that implements Aegis

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  aegis:
    path: ../../aegis
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  flutter_hooks: ^0.18.6
  get_it: ^7.2.0
  go_router: ^6.2.0
  # go_router_flow: ^6.2.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  go_router_builder: ^1.1.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Uni Neue
      fonts:
        - asset: packages/aegis/fonts/uni_neue/UniNeue-Bold.otf
          style: normal
          weight: 700
        - asset: packages/aegis/fonts/uni_neue/UniNeue-HeavyItalic.otf
          style: italic
          weight: 900
        - asset: packages/aegis/fonts/uni_neue/UniNeue-Light.otf
          style: normal
          weight: 300
        - asset: packages/aegis/fonts/uni_neue/UniNeue-Regular.otf
          style: normal
          weight: 400 
