name: aegis
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.6
  flutter_screenutil: ^5.6.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3

  # Form
  form_validator: ^2.1.1

  # Localizations
  intl: ^0.17.0

  # List
  azlistview: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: AegisIcons
      fonts: 
        - asset: lib/fonts/aegis_icons/AegisIcons.ttf
    - family: Uni Neue
      fonts:
        - asset: lib/fonts/uni_neue/UniNeue-Regular.otf
          weight: 400
        - asset: lib/fonts/uni_neue/UniNeue-Light.otf
          weight: 200
        - asset: lib/fonts/uni_neue/UniNeue-Bold.otf
          weight: 600
        - asset: lib/fonts/uni_neue/UniNeue-HeavyItalic.otf
          weight: 700
          style: italic

  assets:
    - assets/svg/
